library(tidyverse)
Final_Data <- Final_Data_Feb_24

#Change gender codes to F, M, NB
Final_Data$Q1[Final_Data$Q1 == "Female"]    <- "F" 
Final_Data$Q1[Final_Data$Q1 == "Male"]      <- "M"
Final_Data$Q1[Final_Data$Q1 == "Nonbinary"] <- "NB"

#Change school name to 2-4 letter code
Final_Data$Q6[Final_Data$Q6 == "Amherst College"]                      <- "AC"
Final_Data$Q6[Final_Data$Q6 == "Andrew's University"]                  <- "AU"
Final_Data$Q6[Final_Data$Q6 == "Andrews University"]                   <- "AU"
Final_Data$Q6[Final_Data$Q6 == "app state"]                            <- "ASU"
Final_Data$Q6[Final_Data$Q6 == "Appalachian State"]                    <- "ASU"
Final_Data$Q6[Final_Data$Q6 == "Appalachian State University"]         <- "ASU"
Final_Data$Q6[Final_Data$Q6 == "Boston University"]                    <- "BNU"
Final_Data$Q6[Final_Data$Q6 == "Bucknell"]                             <- "BLU"
Final_Data$Q6[Final_Data$Q6 == "Cal Poly"]                             <- "CPSU"
Final_Data$Q6[Final_Data$Q6 == "Claremont McKenna College"]            <- "CMC"
Final_Data$Q6[Final_Data$Q6 == "College of the Atlantic"]              <- "CA"
Final_Data$Q6[Final_Data$Q6 == "Columbia University"]                  <- "CU"
Final_Data$Q6[Final_Data$Q6 == "davidson"]                             <- "DC"
Final_Data$Q6[Final_Data$Q6 == "Davidson College"]                     <- "DC"
Final_Data$Q6[Final_Data$Q6 == "DePauw University"]                    <- "DU"
Final_Data$Q6[Final_Data$Q6 == "East Carolina University"]             <- "ECU"
Final_Data$Q6[Final_Data$Q6 == "Ecu"]                                  <- "ECU"
Final_Data$Q6[Final_Data$Q6 == "Florida International University"]     <- "FIU"
Final_Data$Q6[Final_Data$Q6 == "Kalamazoo College"]                    <- "KC"
Final_Data$Q6[Final_Data$Q6 == "Lees-McRae"]                           <- "LMC"
Final_Data$Q6[Final_Data$Q6 == "loyola"]                               <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola"]                               <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola Chicago"]                       <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola Chicago"]                       <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola University at Chicago"]         <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "loyola university chicago"]            <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola University Chicago"]            <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola University of Chicago"]         <- "LUC" 
Final_Data$Q6[Final_Data$Q6 == "Loyola University- Chicago"]           <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "McGill University"]                    <- "MU"
Final_Data$Q6[Final_Data$Q6 == "Messiah college"]                      <- "MC"
Final_Data$Q6[Final_Data$Q6 == "Messiah College"]                      <- "MC"
Final_Data$Q6[Final_Data$Q6 == "NC State"]                             <- "NCSU"
Final_Data$Q6[Final_Data$Q6 == "NC State University"]                  <- "NCSU"
Final_Data$Q6[Final_Data$Q6 == "Ncsu"]                                 <- "NCSU"
Final_Data$Q6[Final_Data$Q6 == "North Carolina State University"]      <- "NCSU"
Final_Data$Q6[Final_Data$Q6 == "Pacific University"]                   <- "PU"
Final_Data$Q6[Final_Data$Q6 == "patzer"]                               <- "PZC"
Final_Data$Q6[Final_Data$Q6 == "Pitzer College"]                       <- "PZC"
Final_Data$Q6[Final_Data$Q6 == "Penn State University"]                <- "PSU"
Final_Data$Q6[Final_Data$Q6 == "Pomona College"]                       <- "PMC"
Final_Data$Q6[Final_Data$Q6 == "Pomona college"]                       <- "PMC"
Final_Data$Q6[Final_Data$Q6 == "Pomona"]                               <- "PMC"
Final_Data$Q6[Final_Data$Q6 == "Rice University"]                      <- "RU"
Final_Data$Q6[Final_Data$Q6 == "Rutgers University"]                   <- "RGU"
Final_Data$Q6[Final_Data$Q6 == "Rutgers"]                              <- "RGU"
Final_Data$Q6[Final_Data$Q6 == "Scripps"]                              <- "SC"
Final_Data$Q6[Final_Data$Q6 == "Scripps college"]                      <- "SC"
Final_Data$Q6[Final_Data$Q6 == "Scripps College"]                      <- "SC"
Final_Data$Q6[Final_Data$Q6 == "St. Mary's College of California"]     <- "SMCC"
Final_Data$Q6[Final_Data$Q6 == "SUNY Oswego"]                          <- "SUNYO"
Final_Data$Q6[Final_Data$Q6 == "Temple university"]                           <- "TMU"
Final_Data$Q6[Final_Data$Q6 == "Tennessee"]                                   <- "UTK"
Final_Data$Q6[Final_Data$Q6 == "University of Tennessee"]                     <- "UTK"
Final_Data$Q6[Final_Data$Q6 == "Tufts University"]                            <- "TU"
Final_Data$Q6[Final_Data$Q6 == "University of Massachusetts, Amherst"]        <- "UMA"
Final_Data$Q6[Final_Data$Q6 == "umass boston"]                                <- "UMB"
Final_Data$Q6[Final_Data$Q6 == "Umass Boston"]                                <- "UMB"
Final_Data$Q6[Final_Data$Q6 == "UMass Boston"]                                <- "UMB"
Final_Data$Q6[Final_Data$Q6 == "UMASS Boston"]                                <- "UMB"
Final_Data$Q6[Final_Data$Q6 == "University of Massachusetts Boston"]          <- "UMB"
Final_Data$Q6[Final_Data$Q6 == "University of Massachusetts - Boston"]        <- "UMB"
Final_Data$Q6[Final_Data$Q6 == "UNC Chapel Hill"]                             <- "UNCCH"
Final_Data$Q6[Final_Data$Q6 == "UNC-Chapel Hill"]                             <- "UNCCH"
Final_Data$Q6[Final_Data$Q6 == "University of North Carolina"]                <- "UNCCH"
Final_Data$Q6[Final_Data$Q6 == "University of North Carolina at Chapel Hill"] <- "UNCCH"
Final_Data$Q6[Final_Data$Q6 == "Unc Charlotte"]                               <- "UNCC"
Final_Data$Q6[Final_Data$Q6 == "UNC Charlotte"]                               <- "UNCC"
Final_Data$Q6[Final_Data$Q6 == "University of Alaska Anchorage"]              <- "UAA"
Final_Data$Q6[Final_Data$Q6 == "University of California Santa Cruz"]         <- "UCSC"
Final_Data$Q6[Final_Data$Q6 == "University of Central Florida"]               <- "UCF"
Final_Data$Q6[Final_Data$Q6 == "University of Florida"]                       <- "UF"
Final_Data$Q6[Final_Data$Q6 == "University of san francisco"]                 <- "USF"
Final_Data$Q6[Final_Data$Q6 == "University of san Francisco"]                 <- "USF"
Final_Data$Q6[Final_Data$Q6 == "University of San Francisco"]                 <- "USF"
Final_Data$Q6[Final_Data$Q6 == "University of South Carolina"]                <- "USC"
Final_Data$Q6[Final_Data$Q6 == "University of south florida"]                 <- "USFL"
Final_Data$Q6[Final_Data$Q6 == "university of vermont"]                       <- "UVT"
Final_Data$Q6[Final_Data$Q6 == "University of Virginia"]                      <- "UVA"
Final_Data$Q6[Final_Data$Q6 == "University of Wisconsin-Stevens Point"]       <- "UWSP"
Final_Data$Q6[Final_Data$Q6 == "Virginia Military Institute"]                 <- "VMI"
Final_Data$Q6[Final_Data$Q6 == "Vmi"]                                         <- "VMI"
Final_Data$Q6[Final_Data$Q6 == "Virginia Military Institiute"]                <- "VMI"
Final_Data$Q6[Final_Data$Q6 == "Virginia Tech"]                               <- "VT"
Final_Data$Q6[Final_Data$Q6 == "virginia tech"]                               <- "VT"
Final_Data$Q6[Final_Data$Q6 == "Washington and Lee University"]               <- "WLU"
Final_Data$Q6[Final_Data$Q6 == "W&l"]                                         <- "WLU"
Final_Data$Q6[Final_Data$Q6 == "W&L"]                                         <- "WLU"
Final_Data$Q6[Final_Data$Q6 == "Washington & Lee"]                            <- "WLU"
Final_Data$Q6[Final_Data$Q6 == "Washington & Lee University"]                 <- "WLU"
Final_Data$Q6[Final_Data$Q6 == "washington and lee"]                          <- "WLU"
Final_Data$Q6[Final_Data$Q6 == "Washington and lee"]                          <- "WLU"
Final_Data$Q6[Final_Data$Q6 == "Washington and Lee"]                          <- "WLU"
Final_Data$Q6[Final_Data$Q6 == "Wake Forest"]                                 <- "WFU"
Final_Data$Q6[Final_Data$Q6 == "Wake Forest University"]                      <- "WFU"
Final_Data$Q6[Final_Data$Q6 == "wake forest university"]                      <- "WFU"
Final_Data$Q6[Final_Data$Q6 == "Wfu"]                                         <- "WFU"
Final_Data$Q6[Final_Data$Q6 == "Warren Wilson College"]                       <- "WWC"
Final_Data$Q6[Final_Data$Q6 == "Western Carolina University"]                 <- "WCU"
Final_Data$Q6[Final_Data$Q6 == "Western Washington University"]               <- "WWU"
Final_Data$Q6[Final_Data$Q6 == "Whitman College"]                             <- "WC"
Final_Data$Q6[Final_Data$Q6 == "Yale University"]                             <- "YU"


