library(tidyverse)
Final_Data <- Final_Data_Feb_24

#Change gender codes to F, M, NB
Final_Data$Q1[Final_Data$Q1 == "Female"]    <- "F" 
Final_Data$Q1[Final_Data$Q1 == "Male"]      <- "M"
Final_Data$Q1[Final_Data$Q1 == "Nonbinary"] <- "NB"

#Change school name to 2-4 letter code
Final_Data$Q6[Final_Data$Q6 == "Amherst College"]                  <- "AC"
Final_Data$Q6[Final_Data$Q6 == "Andrew's University"]              <- "AU"
Final_Data$Q6[Final_Data$Q6 == "Andrews University"]               <- "AU"
Final_Data$Q6[Final_Data$Q6 == "app state"]                        <- "ASU"
Final_Data$Q6[Final_Data$Q6 == "Appalachian State"]                <- "ASU"
Final_Data$Q6[Final_Data$Q6 == "Appalachian State University"]     <- "ASU"
Final_Data$Q6[Final_Data$Q6 == "Boston University"]                <- "BNU"
Final_Data$Q6[Final_Data$Q6 == "Bucknell"]                         <- "BLU"
Final_Data$Q6[Final_Data$Q6 == "Cal Poly"]                         <- "CPSU"
Final_Data$Q6[Final_Data$Q6 == "Claremont McKenna College"]        <- "CMC"
Final_Data$Q6[Final_Data$Q6 == "College of the Atlantic"]          <- "CA"
Final_Data$Q6[Final_Data$Q6 == "Columbia University"]              <- "CU"
Final_Data$Q6[Final_Data$Q6 == "davidson"]                         <- "DC"
Final_Data$Q6[Final_Data$Q6 == "Davidson College"]                 <- "DC"
Final_Data$Q6[Final_Data$Q6 == "DePauw University"]                <- "DU"
Final_Data$Q6[Final_Data$Q6 == "East Carolina University"]         <- "ECU"
Final_Data$Q6[Final_Data$Q6 == "Ecu"]                              <- "ECU"
Final_Data$Q6[Final_Data$Q6 == "Florida International University"] <- "FIU"
Final_Data$Q6[Final_Data$Q6 == "Kalamazoo College"]                <- "KC"
Final_Data$Q6[Final_Data$Q6 == "Lees-McRae"]                       <- "LMC"
Final_Data$Q6[Final_Data$Q6 == "loyola"]                           <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola"]                           <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola Chicago"]                   <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola Chicago"]                   <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola University at Chicago"]     <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "loyola university chicago"]        <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola University Chicago"]        <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "Loyola University of Chicago"]     <- "LUC" 
Final_Data$Q6[Final_Data$Q6 == "Loyola University- Chicago"]       <- "LUC"
Final_Data$Q6[Final_Data$Q6 == "McGill University"]                <- "MU"
Final_Data$Q6[Final_Data$Q6 == "Messiah college"]                  <- "MC"
Final_Data$Q6[Final_Data$Q6 == "Messiah College"]                  <- "MC"
Final_Data$Q6[Final_Data$Q6 == "NC State"]                         <- "NCSU"
Final_Data$Q6[Final_Data$Q6 == "NC State University"]              <- "NCSU"
Final_Data$Q6[Final_Data$Q6 == "Ncsu"]                             <- "NCSU"
Final_Data$Q6[Final_Data$Q6 == "North Carolina State University"]  <- "NCSU"
Final_Data$Q6[Final_Data$Q6 == "Washington and Lee University"]    <- "WLU"

